rose_map:
  ros__parameters:
    odom_topic: /Odometry
    rose_map:
      log_time: true
      pointcloud_topic: /cloud_registered
      sensor_frame: front_mid360
      max_update_rate: 10
      origin: [0.0, 0.0, 0.0]
      size: [12.0, 12.0, 1.0]
      voxel_size: 0.02
      occ_map:
        log_hit: 0.85
        log_free: -0.3
        log_min: -5.0
        log_max: 10.0
        occ_th: 0.0       
        min_shift: 2
        timeout: 1.5
        unknown_is_occupied: false
        use_ray: true
        max_ray_range: 20.0
      acc_map:
        origin2base: 0.0
        min_diff_z: 0.0
        min_block_count: 1
        block_ratio: 0.1
        kernel_size: 5
        dilate_iter: 2
        use_static_map: false
        static_map_path: ""
      esdf:
        use_diagonals: true
      inf_map:
        inflation_step: 1