rose_map:
  ros__parameters:
    rose_map:
      odom_topic: /Odometry
      pointcloud_topic: /cloud_registered
      sensor_frame: front_mid360
      max_update_rate: 10
      origin: [0.0, 0.0, 0.0]
      size: [12.0, 12.0, 1.0]
      voxel_size: 0.05
      occ_map:
        log_hit: 0.85
        log_free: -0.3
        log_min: -5.0
        log_max: 5.0
        occ_th: 0.0        # â‰ˆ P > 0.77
        min_shift: 2
        timeout: 1.5
        max_ray_range: 20.0
        unknown_is_occupied: false
        use_ray: false
      acc_map:
        origin2base: 0.1
        min_diff_z: -0.10
        min_block_count: 1
        block_ratio: 0.15
      esdf:
        use_diagonals: true